### ISSUE TITLE
[getEndIndex] possible bug for totalItems = 1

### ISSUE THREAD

**Issue by JonasBa** [erictooth/react-use-pagination#2]
I've glanced through the codebase and I think I may have found potential bug in the implementation of getEndIndex in a corner case when `totalItems = 0`. The current implementation of getEndIndex would return a startIndex and endIndex of `0` as `(totalItems - 1) = 1 - 1 = 0`. If users of this library rely on on using arr.slice to paginate their data (which seems like the obvious case), calling `arr.slice(0,0)` evaluates `[]` and so the 1 item would not get rendered.

I've made a quick codesandbox to demonstrate the issue (and the fix) [here](https://codesandbox.io/s/young-dream-c6pxb?file=/src/index.ts). Hope I've been clear enough and please feel free to correct me if I'm wrong :)

**Comment by devshahrukhkhan** [comment]
Hi i have faced this issue today!
has it been fixed?
i am using `"react-use-pagination": "^2.0.1"`


To overcome this i did something like this

`data.slice(startIndex, data.length === 1 ? 1 : endIndex)`

is that ok?
