### ISSUE TITLE
Concerns about using this package

### ISSUE THREAD

**Issue by asplunds** [erictooth/react-use-pagination#9]
I initially wanted to skip having to write pagination logic myself so I wanted to use this hook but now I've reconsidered after attempting to implement this.

Passing `initialPageSize` simply does not work, whatever I do the page size is always 3 for some reason. Additionally, calling `setPageSize` does nothing either.

Furthermore, why is the page size state encapsulated inside the hook? This is not idiomatic at all, `setPageSize` and `initialPageSize` should not exist, that state (if it even is a state) should be at the implementation level and passed down React-like, not puppeteering a child state with parent state (very frustrating).

Why can't we just pass in the page size, current page and let the hook give back logic about previous, upcoming and total pages?! The library should help me implement my pagination, not control it.

I will write my own package now but I write this in hopes that 2.0 will have a more idiomatic and agnostic API.

sidenote: [Try out an example on CodeSandbox](https://codesandbox.io/s/react-use-pagination-example-30jy6) does not work

**Comment by asplunds** [comment]
I made a package for people who are having the same concerns as me, it's brutally simple: https://github.com/asplunds/use-paginate

**Comment by erictooth** [comment]
Weird, all of the tests involving `initialPageSize` are still passing and I saw no issues when I just checked the latest version in a couple of projects using it. Glad this project could serve as inspiration to make your own!

**Comment by Divinebosst** [comment]
Thank you very much @asplunds . This package seems to have many bugs.
